=== crocs-muni/sec-certs/src/sec_certs/serialization/schemas/fips_certificate.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://sec-certs.org/schemas/fips_certificate.json",
  "title": "FIPS 140 Certificate",
  "description": "Schema for a FIPS 140 certificate.",
  "type": "object",
  "definitions": {
    "fips_dgst": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{16}$",
      "title": "Certificate Digest",
      "description": "A hex string representing 8 bytes."
    },
    "fips_id": {
      "type": "integer",
      "minimum": 0,
      "title": "Certificate ID",
      "description": "A non-negative integer representing the certificate ID."
    },
    "fips_str_id": {
      "type": "string",
      "pattern": "^[0-9]+$",
      "title": "Certificate ID",
      "description": "A non-negative integer representing the certificate ID, in string form."
    },
    "fips_references": {
      "type": "object",
      "properties": {
        "_type": {
          "const": "sec_certs.sample.certificate.References"
        },
        "directly_referenced_by": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          },
          "description": "Certificates that directly reference this certificate."
        },
        "indirectly_referenced_by": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          },
          "description": "Certificates that indirectly reference this certificate."
        },
        "directly_referencing": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          },
          "description": "Certificates that are directly referenced by this certificate."
        },
        "indirectly_referencing": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          },
          "description": "Certificates that are indirectly referenced by this certificate."
        }
      }
    },
    "br1_table": {
      "type": "object",
      "properties": {
        "section": { "type": "integer" },
        "subsection": { "type": "integer" },
        "found": { "type": "boolean" },
        "entries": { "type": "array", "items": { "type": "object" } }
      },
      "required": ["section", "subsection", "found", "entries"]
    },
    "br1_tables_class": {
      "type": "object",
      "properties": {
        "security_levels": { "$ref": "#/definitions/br1_table" },
        "tested_module_id_hw": { "$ref": "#/definitions/br1_table" },
        "tested_module_id_sw_fw_hy": { "$ref": "#/definitions/br1_table" },
        "tested_module_id_hw_hy": { "$ref": "#/definitions/br1_table" },
        "tested_op_env_sw_fw_hy": { "$ref": "#/definitions/br1_table" },
        "vendor_affirmed_op_env_sw_fw_hy": { "$ref": "#/definitions/br1_table" },
        "modes_of_operation": { "$ref": "#/definitions/br1_table" },
        "approved_algorithms": { "$ref": "#/definitions/br1_table" },
        "vendor_affirmed_algos": { "$ref": "#/definitions/br1_table" },
        "non_approved_allowed_algos": { "$ref": "#/definitions/br1_table" },
        "non_approved_allowed_NSC": { "$ref": "#/definitions/br1_table" },
        "non_approved_not_allowed": { "$ref": "#/definitions/br1_table" },
        "ports_interfaces": { "$ref": "#/definitions/br1_table" },
        "authentication_methods": { "$ref": "#/definitions/br1_table" },
        "approved_services": { "$ref": "#/definitions/br1_table" },
        "non_approved_services": { "$ref": "#/definitions/br1_table" },
        "mechanisms_actions": { "$ref": "#/definitions/br1_table" },
        "storage_areas": { "$ref": "#/definitions/br1_table" },
        "ssp_io_methods": { "$ref": "#/definitions/br1_table" },
        "ssp_zeroization_methods": { "$ref": "#/definitions/br1_table" },
        "self_tests": { "$ref": "#/definitions/br1_table" },
        "error_states": { "$ref": "#/definitions/br1_table" }
      },
      "required": [
        "security_levels",
        "tested_module_id_hw",
        "tested_module_id_sw_fw_hy",
        "tested_module_id_hw_hy",
        "tested_op_env_sw_fw_hy",
        "vendor_affirmed_op_env_sw_fw_hy",
        "modes_of_operation",
        "approved_algorithms",
        "vendor_affirmed_algos",
        "non_approved_allowed_algos",
        "non_approved_allowed_NSC",
        "non_approved_not_allowed",
        "ports_interfaces",
        "authentication_methods",
        "approved_services",
        "non_approved_services",
        "mechanisms_actions",
        "storage_areas",
        "ssp_io_methods",
        "ssp_zeroization_methods",
        "self_tests",
        "error_states"
      ]
    }
  },
  "properties": {
    "_type": {
      "const": "sec_certs.sample.fips.FIPSCertificate"
    },
    "dgst": {
      "$ref": "#/definitions/fips_dgst"
    },
    "cert_id": {
      "$ref": "#/definitions/fips_id"
    },
    "web_data": {
      "type": "object",
      "properties": {
        "_type": {
          "const": "sec_certs.sample.fips.FIPSCertificate.WebData"
        },
        "module_name": {
          "type": [
            "string",
            "null"
          ],
          "title": "Module Name",
          "description": "The name of the certified module."
        },
        "validation_history": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "object",
            "properties": {
              "_type": {
                "const": "sec_certs.sample.fips.FIPSCertificate.ValidationHistoryEntry"
              },
              "date": {
                "type": "string",
                "format": "date",
                "description": "The date of the validation event in YYYY-MM-DD format."
              },
              "validation_type": {
                "enum": [
                  "Initial",
                  "Update"
                ],
                "description": "The type of validation event."
              },
              "lab": {
                "type": "string",
                "description": "The name of the lab that performed the validation."
              }
            },
            "additionalProperties": false
          }
        },
        "vendor_url": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri",
          "title": "Vendor URL",
          "description": "The URL of the vendor's website."
        },
        "vendor": {
          "type": [
            "string",
            "null"
          ],
          "title": "Vendor Name",
          "description": "The name of the vendor of the module."
        },
        "certificate_pdf_url": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri",
          "title": "Certificate PDF URL",
          "description": "The URL of the certificate PDF document."
        },
        "module_type": {
          "enum": [
            "Firmware",
            "Firmware-Hybrid",
            "Hardware",
            "Software",
            "Software-Hybrid",
            "Hybrid",
            null
          ],
          "title": "Certified Module Type",
          "description": "The type of the certified module."
        },
        "standard": {
          "enum": [
            "FIPS 140-1",
            "FIPS 140-2",
            "FIPS 140-3",
            null
          ],
          "title": "FIPS Standard",
          "description": "The FIPS standard under which the module was certified."
        },
        "status": {
          "enum": [
            "active",
            "historical",
            "revoked",
            null
          ],
          "title": "Certificate Status",
          "description": "The current status of the certificate."
        },
        "level": {
          "type": [
            "integer",
            "null"
          ],
          "minimum": 1,
          "maximum": 4,
          "title": "Security Level",
          "description": "The security level of the certified module (1 to 4)."
        },
        "caveat": {
          "type": [
            "string",
            "null"
          ],
          "title": "Caveat",
          "description": "Any caveats associated with the certification."
        },
        "exceptions": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "title": "Exceptions",
          "description": "Any exceptions associated with the certification."
        },
        "embodiment": {
          "anyOf": [
            {
              "enum": [
                "Multi-Chip Stand Alone",
                "Multi-Chip Embedded",
                "Single Chip",
                "*"
              ]
            },
            {
              "type": "null"
            }
          ],
          "title": "Embodiment",
          "description": "The embodiment of the certified module."
        },
        "description": {
          "type": [
            "string",
            "null"
          ],
          "title": "Module Description",
          "description": "A brief description of the certified module."
        },
        "tested_conf": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "title": "Tested Configurations",
          "description": "The tested configuration(s) of the certified module."
        },
        "hw_versions": {
          "type": [
            "string",
            "null"
          ],
          "title": "Hardware Versions",
          "description": "The hardware version(s) of the certified module."
        },
        "fw_versions": {
          "type": [
            "string",
            "null"
          ],
          "title": "Firmware Versions",
          "description": "The firmware version(s) of the certified module."
        },
        "sw_versions": {
          "type": [
            "string",
            "null"
          ],
          "title": "Software Versions",
          "description": "The software version(s) of the certified module."
        },
        "mentioned_certs": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          },
          "title": "Mentioned Certificates",
          "description": "Other FIPS certificates mentioned in the module page."
        },
        "historical_reason": {
          "type": [
            "string",
            "null"
          ],
          "title": "Historical Reason",
          "description": "The reason why the certificate is marked as historical (if any)."
        },
        "date_sunset": {
          "type": [
            "string",
            "null"
          ],
          "format": "date",
          "title": "Sunset Date",
          "description": "The date when the certificate was sunsetted/revoked/archived (YYYY-MM-DD)."
        },
        "revoked_reason": {
          "type": [
            "string",
            "null"
          ],
          "title": "Revocation Reason",
          "description": "The reason why the certificate was revoked (if any)."
        },
        "revoked_link": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri",
          "title": "Revocation Link",
          "description": "A link to more information about the revocation (if any)."
        }
      }
    },
    "pdf_data": {
      "type": "object",
      "properties": {
        "_type": {
          "const": "sec_certs.sample.fips.FIPSCertificate.PdfData"
        },
        "keywords": {
          "$ref": "base.json#/definitions/document_keywords",
          "title": "Security Policy Keywords",
          "description": "Keywords extracted from the security policy document."
        },
        "policy_metadata": {
          "$ref": "base.json#/definitions/document_metadata",
          "title": "Security Policy Metadata",
          "description": "Metadata extracted from the security policy document."
        }
      },
      "title": "Extracted PDF Data",
      "description": "Data extracted from the certification PDF document (security policy)."
    },
    "heuristics": {
      "type": "object",
      "properties": {
        "_type": {
          "const": "sec_certs.sample.fips.FIPSCertificate.Heuristics"
        },
        "algorithms": {
          "type": "object",
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "extracted_versions": {
          "$ref": "base.json#/definitions/extracted_versions"
        },
        "cpe_matches": {
          "$ref": "base.json#/definitions/cpe_matches"
        },
        "verified_cpe_matches": {
          "$ref": "base.json#/definitions/verified_cpe_matches"
        },
        "related_cves": {
          "$ref": "base.json#/definitions/related_cves"
        },
        "policy_prunned_references": {
          "type": "object",
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          }
        },
        "module_prunned_references": {
          "type": "object",
          "properties": {
            "_type": {
              "const": "Set"
            },
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/fips_str_id"
              },
              "uniqueItems": true
            }
          }
        },
        "policy_processed_references": {
          "$ref": "#/definitions/fips_references",
          "description": "References to and from other certificates, based on the security policy document."
        },
        "module_processed_references": {
          "$ref": "#/definitions/fips_references",
          "description": "References to and from other certificates, based on the module page."
        },
        "direct_transitive_cves": {
          "$ref": "base.json#/definitions/direct_transitive_cves"
        },
        "indirect_transitive_cves": {
          "$ref": "base.json#/definitions/indirect_transitive_cves"
        },
        "is_br1_format": {
          "type": "boolean"
        },
        "br1_deviations": {
          "type": "integer",
          "minimum": 0
        },
        "br1_tables": {
          "description": "Data structure holding BR1 tables.",
          "anyOf": [
            { "type": "null" },
            { "$ref": "#/definitions/br1_tables_class" }
          ]
        }
      },
      "additionalProperties": false,
      "title": "Certificate Heuristics",
      "description": "Heuristic data extracted from the certification documents."
    },
    "state": {
      "type": "object",
      "properties": {
        "_type": {
          "const": "sec_certs.sample.fips.FIPSCertificate.InternalState"
        },
        "module_download_ok": {
          "type": "boolean"
        },
        "policy_download_ok": {
          "type": "boolean"
        },
        "policy_convert_garbage": {
          "type": "boolean"
        },
        "policy_convert_ok": {
          "type": "boolean"
        },
        "module_extract_ok": {
          "type": "boolean"
        },
        "policy_extract_ok": {
          "type": "boolean"
        },
        "policy_pdf_hash": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{64}$",
          "description": "SHA256 hash of the policy PDF file."
        },
        "policy_txt_hash": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{64}$",
          "description": "SHA256 hash of the policy txt file."
        }
      },
      "additionalProperties": false,
      "title": "Certificate Document States",
      "description": "State of the document processing pipeline for policy and module documents."
    }
  },
  "additionalProperties": false
}

=== crocs-muni/sec-certs/tests/data/fips/certificate/fictional_cert.json
{
    "_type": "sec_certs.sample.fips.FIPSCertificate",
    "dgst": "184097a88a9b4ad9",
    "cert_id": 3518,
    "web_data": {
        "_type": "sec_certs.sample.fips.FIPSCertificate.WebData",
        "module_name": null,
        "validation_history": null,
        "vendor_url": null,
        "vendor": null,
        "certificate_pdf_url": null,
        "module_type": null,
        "standard": null,
        "status": null,
        "level": null,
        "caveat": null,
        "exceptions": null,
        "embodiment": null,
        "description": null,
        "tested_conf": null,
        "hw_versions": null,
        "fw_versions": null,
        "sw_versions": null,
        "mentioned_certs": null,
        "historical_reason": null,
        "date_sunset": null,
        "revoked_reason": null,
        "revoked_link": null
    },
    "pdf_data": {
        "_type": "sec_certs.sample.fips.FIPSCertificate.PdfData",
        "keywords": {},
        "policy_metadata": {}
    },
    "heuristics": {
        "_type": "sec_certs.sample.fips.FIPSCertificate.Heuristics",
        "algorithms": {
            "_type": "Set",
            "elements": []
        },
        "extracted_versions": {
            "_type": "Set",
            "elements": []
        },
        "cpe_matches": null,
        "verified_cpe_matches": null,
        "related_cves": null,
        "policy_prunned_references": {
            "_type": "Set",
            "elements": []
        },
        "module_prunned_references": {
            "_type": "Set",
            "elements": []
        },
        "policy_processed_references": {
            "_type": "sec_certs.sample.certificate.References",
            "directly_referenced_by": null,
            "indirectly_referenced_by": null,
            "directly_referencing": null,
            "indirectly_referencing": null
        },
        "module_processed_references": {
            "_type": "sec_certs.sample.certificate.References",
            "directly_referenced_by": null,
            "indirectly_referenced_by": null,
            "directly_referencing": null,
            "indirectly_referencing": null
        },
        "direct_transitive_cves": null,
        "indirect_transitive_cves": null,
        "is_br1_format": false,
        "br1_deviations": 0,
        "br1_tables": null
    },
    "state": {
        "_type": "sec_certs.sample.fips.FIPSCertificate.InternalState",
        "module_download_ok": true,
        "policy_download_ok": true,
        "policy_convert_garbage": false,
        "policy_convert_ok": true,
        "module_extract_ok": false,
        "policy_extract_ok": false,
        "policy_pdf_hash": "36b63890182f0aed29b305a0b4acc0d70b657262516f4be69138c70c2abdb1f1",
        "policy_txt_hash": "cc1f8d0f7bb759894e81cbbfd1cfe02cdc443879fd47d3306f2a1b419fbf2872"
    }
}
